//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.04 at 01:58:37 PM IST 
//


package com.resteasy.services.model.virtualmachine;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dateAndTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hostName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="physicalSwitchAndPorts" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dateAndTime",
    "hostName",
    "physicalSwitchAndPorts"
})
@XmlRootElement(name = "vmNetworkLocationHistory")
public class VmNetworkLocationHistory {

    @XmlElement(required = true)
    protected String dateAndTime;
    @XmlElement(required = true)
    protected String hostName;
    @XmlElement(required = true)
    protected String physicalSwitchAndPorts;

    public VmNetworkLocationHistory() {
		// TODO Auto-generated constructor stub
	}
    
    /**
     * 
     * @param dateAndTime
     * @param hostName
     * @param physicalSwitchAndPorts
     */
    public VmNetworkLocationHistory(String dateAndTime, String hostName,
			String physicalSwitchAndPorts) {
		super();
		this.dateAndTime = dateAndTime;
		this.hostName = hostName;
		this.physicalSwitchAndPorts = physicalSwitchAndPorts;
	}

	/**
     * Gets the value of the dateAndTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateAndTime() {
        return dateAndTime;
    }

    /**
     * Sets the value of the dateAndTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateAndTime(String value) {
        this.dateAndTime = value;
    }

    /**
     * Gets the value of the hostName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHostName() {
        return hostName;
    }

    /**
     * Sets the value of the hostName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHostName(String value) {
        this.hostName = value;
    }

    /**
     * Gets the value of the physicalSwitchAndPorts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhysicalSwitchAndPorts() {
        return physicalSwitchAndPorts;
    }

    /**
     * Sets the value of the physicalSwitchAndPorts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhysicalSwitchAndPorts(String value) {
        this.physicalSwitchAndPorts = value;
    }

}
