//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.30 at 03:04:30 PM IST 
//


package com.resteasy.services.model.host;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}nic"/>
 *         &lt;element ref="{}up"/>
 *         &lt;element ref="{}switchId"/>
 *         &lt;element ref="{}port"/>
 *         &lt;element ref="{}vlansAllowPort"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nic",
    "up",
    "switchId",
    "port",
    "vlansAllowPort"
})
@XmlRootElement(name = "hostNetworkingData")
public class HostNetworkingData {

    @XmlElement(required = true)
    protected String nic;
    @XmlElement(required = true)
    protected int up;
    @XmlElement(required = true)
    protected String switchId;
    @XmlElement(required = true)
    protected String port;
    @XmlElement(required = true)
    protected String vlansAllowPort;

    public HostNetworkingData() {
		// TODO Auto-generated constructor stub
	}
    
    public HostNetworkingData(String nic, int i, String switchId,
			String port, String vlansAllowPort) {
		super();
		this.nic = nic;
		this.up = i;
		this.switchId = switchId;
		this.port = port;
		this.vlansAllowPort = vlansAllowPort;
	}


	/**
     * Gets the value of the nic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNic() {
        return nic;
    }

    /**
     * Sets the value of the nic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNic(String value) {
        this.nic = value;
    }

    /**
     * Gets the value of the up property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public int getUp() {
        return up;
    }

    /**
     * Sets the value of the up property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUp(int value) {
        this.up = value;
    }

    /**
     * Gets the value of the switchId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSwitchId() {
        return switchId;
    }

    /**
     * Sets the value of the switchId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwitchId(String value) {
        this.switchId = value;
    }

    /**
     * Gets the value of the port property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPort() {
        return port;
    }

    /**
     * Sets the value of the port property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPort(String value) {
        this.port = value;
    }

    /**
     * Gets the value of the vlansAllowPort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVlansAllowPort() {
        return vlansAllowPort;
    }

    /**
     * Sets the value of the vlansAllowPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVlansAllowPort(String value) {
        this.vlansAllowPort = value;
    }

}
