//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.30 at 03:04:30 PM IST 
//


package com.resteasy.services.model.host;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}hostNetworkingData" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hostNetworkingData"
})
@XmlRootElement(name = "hostNetworkingDataList")
public class HostNetworkingDataList {

    @XmlElement(required = true)
    protected List<HostNetworkingData> hostNetworkingData;
    
    public HostNetworkingDataList() {
		// TODO Auto-generated constructor stub
	}
    
    public HostNetworkingDataList(List<HostNetworkingData> hostNetworkingData) {
		super();
		this.hostNetworkingData = hostNetworkingData;
	}



	/**
     * Gets the value of the hostNetworkingData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hostNetworkingData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHostNetworkingData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HostNetworkingData }
     * 
     * 
     */
    public List<HostNetworkingData> getHostNetworkingData() {
        if (hostNetworkingData == null) {
            hostNetworkingData = new ArrayList<HostNetworkingData>();
        }
        return this.hostNetworkingData;
    }

}
