//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.30 at 03:04:30 PM IST 
//


package com.resteasy.services.model.host;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.resteasy.services.model.host package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Port_QNAME = new QName("", "port");
    private final static QName _VlansAllowPort_QNAME = new QName("", "vlansAllowPort");
    private final static QName _Nic_QNAME = new QName("", "nic");
    private final static QName _SwitchId_QNAME = new QName("", "switchId");
    private final static QName _Up_QNAME = new QName("", "up");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.resteasy.services.model.host
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HostNetworkingDataList }
     * 
     */
    public HostNetworkingDataList createHostNetworkingDataList() {
        return new HostNetworkingDataList();
    }

    /**
     * Create an instance of {@link HostNetworkingData }
     * 
     */
    public HostNetworkingData createHostNetworkingData() {
        return new HostNetworkingData();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "port")
    public JAXBElement<String> createPort(String value) {
        return new JAXBElement<String>(_Port_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "vlansAllowPort")
    public JAXBElement<String> createVlansAllowPort(String value) {
        return new JAXBElement<String>(_VlansAllowPort_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "nic")
    public JAXBElement<String> createNic(String value) {
        return new JAXBElement<String>(_Nic_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "switchId")
    public JAXBElement<String> createSwitchId(String value) {
        return new JAXBElement<String>(_SwitchId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "up")
    public JAXBElement<BigInteger> createUp(BigInteger value) {
        return new JAXBElement<BigInteger>(_Up_QNAME, BigInteger.class, null, value);
    }

}
